name: airpedia
version: 1.0.6+6
publish_to: none
description: Airline Ticket Booking Application.
environment:
  sdk: ">=3.1.0 <5.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  cloud_firestore: ^6.0.2
  colored_json: ^1.1.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  dropdown_button2: ^2.0.0
  easy_mask: ^2.0.1
  equatable: ^2.0.5
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localization: ^0.3.3
  flutter_screenutil: ^5.6.0
  flutter_spinkit: ^5.1.0
  flutter_typeahead: ^5.0.1
  fluttertoast: ^9.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: any
  jwt_decoder: ^2.0.1
  package_info_plus: any
  path: any
  permission_handler: ^12.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter:
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
  uses-material-design: true
