name: airpedia
version: 1.0.0+5
publish_to: none
description: Airline Ticket Booking Application.
environment:
  sdk: ">=3.1.0 <=4.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.1.0
  colored_json: ^1.1.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  dropdown_button2: ^2.0.0
  easy_mask: ^2.0.1
  equatable: ^2.0.5
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_jailbreak_detection: ^1.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.0
  flutter_screenutil: ^5.6.0
  flutter_spinkit: ^5.1.0
  flutter_typeahead: ^5.0.1
  fluttertoast: ^8.1.1
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: any
  jwt_decoder: ^2.0.1
  package_info_plus: any
  path: any
  permission_handler: ^11.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter:
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
  uses-material-design: true
