// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZUhb25VeuVf9-OWy-gd9gBKzSrGPySRc',
    appId: '1:103733755346:web:45010945faa14edb8d9c0b',
    messagingSenderId: '103733755346',
    projectId: 'airpedia-b2fb4',
    authDomain: 'airpedia-b2fb4.firebaseapp.com',
    storageBucket: 'airpedia-b2fb4.appspot.com',
    measurementId: 'G-5JW315H67B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp-WZ0cqYSQ4I1kHPIeAuR8Wn69MM84fA',
    appId: '1:103733755346:android:6b9400acb3e7a97f8d9c0b',
    messagingSenderId: '103733755346',
    projectId: 'airpedia-b2fb4',
    storageBucket: 'airpedia-b2fb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDktU2U0tSc5BU_tphEyeOG47XXXznj830',
    appId: '1:103733755346:ios:67dfd2b7afe47ce48d9c0b',
    messagingSenderId: '103733755346',
    projectId: 'airpedia-b2fb4',
    storageBucket: 'airpedia-b2fb4.appspot.com',
    iosClientId:
        '103733755346-d6v5uf256onfntbskb6bcgstjd48vb7j.apps.googleusercontent.com',
    iosBundleId: 'com.fathdotdev.airpedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDktU2U0tSc5BU_tphEyeOG47XXXznj830',
    appId: '1:103733755346:ios:67dfd2b7afe47ce48d9c0b',
    messagingSenderId: '103733755346',
    projectId: 'airpedia-b2fb4',
    storageBucket: 'airpedia-b2fb4.appspot.com',
    iosClientId:
        '103733755346-d6v5uf256onfntbskb6bcgstjd48vb7j.apps.googleusercontent.com',
    iosBundleId: 'com.fathdotdev.airpedia',
  );
}
